<?php
$blocklist = array(
    "union",
    "select",
    "insert",
    "delete",
    "drop",
    "update",
    "alter",
    "create",
    "handler",
    "rename",
    "truncate",
    "replace",
    "lock",
    "show",
    "grant",
    "revoke",
    "set",
    "commit",
    "rollback",
    "savepoint",
    "begin",
    "declare",
    "call",
    "execute",
    "prepare",
    "load",
    "file",
    "data",
    "into",
    "table",
    "from",
    "where",
    "limit",
    "offset",
    "order",
    "group",
    "having",
    "procedure",
    "function",
    "return",
    "loop",
    "while",
    "repeat",
    "until",
    "leave",
    "iterate",
    "cursor",
    "open",
    "fetch",
    "close",
    "out",
    "inout",
    "in",
    "as",
    "is",
    "do",
    "break",
    "exit",
    "continue",
    "if",
    "then",
    "else",
    "elseif",
    "case",
    "end",
    "when",
    "else",
    "for",
    "each",
    "using",
    "collate",
    "binary",
    "charset",
    "national",
    "ascii",
    "unicode",
    "utf8",
    "utf16",
    "utf32",
    "utf8mb4",
    "utf16le",
    "utf16be",
    "utf32le",
    "utf32be",
    "ascii_general",
    "ascii_bin",
    "latin1_general",
    "latin1_bin",
    "latin2_general",
    "latin2_bin",
    "latin5_general",
    "latin5_bin",
    "latin7_general",
    "latin7_bin",
    "cp1250_general",
    "cp1250_bin",
    "cp1251_general",
    "cp1251_bin",
    "cp1256_general",
    "cp1256_bin",
    "cp1257_general",
    "cp1257_bin",
    "cp850_general",
    "cp850_bin",
    "cp852_general",
    "cp852_bin",
    "cp866_general",
);

$waf_rules = array(
    '/union\s+select/i', // SQL Injection
    '/select.*from/i', // SQL Injection
    '/insert\s+into/i', // SQL Injection
    '/delete\s+from/i', // SQL Injection
    '/drop\s+table/i', // SQL Injection
    '/update\s+set/i', // SQL Injection
    '/<script.*?>.*?<\/script>/i', // XSS
    '/<.*?on\w+=.*?>/i', // XSS
    '/javascript:/i', // XSS
    '/<iframe.*?>.*?<\/iframe>/i', // XSS
    // ...add more rules as needed...
);
?>
